spring:
  r2dbc:
    url: r2dbc:mysql://172.25.166.90:3306/test
    username: root
    password: 1234
  application:
    name: payment-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false

PSP:
  toss:
    secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    url:  https://api.tosspayments.com

logging:
  level:
    org:
      springframework:
        web: DEBUG
        r2dbc: DEBUG
        transaction: DEBUG
